# Generated by Django 3.1.6 on 2025-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mstuser',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=12)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=45)),
                ('pwd', models.CharField(max_length=13)),
                ('role', models.CharField(max_length=13)),
            ],
        ),
    ]
