# Generated by Django 3.1.6 on 2025-08-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batchid', models.AutoField(primary_key=True, serialize=False)),
                ('batchtitle', models.CharField(max_length=20)),
                ('batchtime', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('facultyname', models.CharField(max_length=25)),
                ('batchstatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('coursedetails', models.CharField(max_length=200)),
                ('courseicon', models.CharField(max_length=60)),
            ],
        ),
    ]
